[gcp_service_account]
type = "service_account"
project_id = "indigo-bazaar-463313-m6"
private_key_id = "a2a858a7e6f94f05ee8328b60371220ad489cc9b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCYzLGSkhl6q0m3
dy29eQxQY8tDzE8Y7mfojTXIo/pPkoN8Y2Tgq6awTpCUIcFycwkNm1BCbMS6nRWb
1ldEbXuE88pFv1ObpsS4DPH8i3auR+JuXL20tOxr8iE3us9kbR035mIGG15C7FwK
PAorq86+mgS49RIkhmcff6plohoQjcGfLFD9bV1ekOxLcJzfO6oVysXDNWte1uwb
F5dsETiWrnRMgNmcztgBksr3JDQ6/S+kBrY//tN2bM7fLWtqcZFd0J6MSy3nyBde
u5sEmRmIbWnzw8TmyTBIBZOri8nt6xaNCAaRWfLgOT8jp37IUoZBgt+LF7izIvct
36G9uhbzAgMBAAECggEAQjBhN3GsMdQjEaNBoBLgf65K7aqCFPWo8zbANpK5qmB4
LpjLqPsSMMtHm7NnndEw+cDuqmd9bK0BIElf8hdO60/DriTr7b/29Rc+d7xeA67F
6jKoRrAcvcHcG80Da6hMgNt+WNDgKzNBx3ksmrBI1Y3YP9qBKmtCHoXp5S6sBcEG
vciALk0lXkRMKN0+UZ5+On+yoGQI4yj127sT9iLRnxDrXG8Z+tO3IIr2XpdJ3+3g
PTuHIf06te9UQczKqH1cvg5d3GSaxgPllG5odn/1sbxKzyDVRQ3pWgZfDVZxLVWi
pji5WN7OY1lCbX6CMm+unrfFO41iXMkZ9BO0ujyjaQKBgQDOddgzfdD6hZeP/n51
sdFz872hY29G3kGWYGzhpxF0TbGX3zACUQ802SS69kKpzlZik7Esp5UCjsoZVPCw
/riv0NC1VxfngLNUfO/FXkLXHj0gMGLTCI7TLge/YjTo636NUhF8MqUGUkFkMVa0
6enkbo/LvijlbRw4cr0odyLy/QKBgQC9dqbxJt2vdQkHfSHYaPyYXI7b2p1O+Sry
Aa5K9FNH3JLUGcE23WTrwZDMjAZ7Rd6E5Sj6dGcj+SgIRB24vbEYx5hKbbDzlGNs
3EJxl2+kZL38RXgwQv9uHkcBlZsHdmH3tLlZ4tcEZUi3x7wzH1hrAvbv8+a8vwCB
2gp9HiSsrwKBgQCh5xXZI0P7AUIegEMpBn2rASvm4HQFzgr+4rTfq8TrQHYRE8ux
NWHIXrQIDU+vm4hwm0MoMm6O5+yiOtLY6ZdpAEZ6vkaXm3yFt8fLLaUazrK+iFMn
DKH8By+6LEgzk2DVb9MYYxq4P07aRDqreneZU/5dlsy5RXwI5ClkDzEP/QKBgQCO
re4mqUhFO/Piyd9VJCslan7DHq1crdQjkBR7qeeVtIx2YjbZZHz99jVfdQvkhcd/
eTwU8NhDhP0azIE9gMz/hkAvvM+Hf/YoIu9+r7aJrLxOYNqULcBCY1bB4LJxOjuo
2VbEVEnsq4HJtQcL0M07OW5RYfIfrg9pupQviSXBTQKBgF2wBTr4O5wQTzv9U8dX
cOJBz7l/eQ7IGCcYAo3ekBw4ONfozggdxDzk68ANloj4jOrNl5qz+xY/UpU8P3L2
KYC+pDJxyy8+zI92LCIJYtjwnBFq2T2e1AA/N3jdYcGjvYVTcGtqRnOExvVDU1Xc
RQYQOpMLYP/Pf+7tGZv/N+Gj
-----END PRIVATE KEY-----"""
client_email = "viki-146@indigo-bazaar-463313-m6.iam.gserviceaccount.com"
client_id = "117512599519004675092"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/viki-146%40indigo-bazaar-463313-m6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
